### ISSUE TITLE
Only prevent when playing video

### ISSUE THREAD

**Issue by tkh23** [graysky2/kodi-prevent-xscreensaver#2]
I like to have kodi autostart and open on one of my workspaces all the time, but then my screensaver never starts. Would it be possible to add the feature that it will only prevent xscreensaver when a video is playing?

**Comment by graysky2** [comment]
Possible, yes, but I have no plans to work on this script any longer.  I believe kodi should run as unprivileged user in its own space thus not needing a util like this any more.
