### ISSUE TITLE
Script not working because of different process name

### ISSUE THREAD

**Issue by todestoast** [graysky2/kodi-prevent-xscreensaver#3]
Hi, thanks for the script. Worked always fine but then suddenly stopped. The reason:

`pidof kodi.bin` returned nothing because the process of my kodi version is called `kodi-x11`. Maybe you could include that in your script. I would do a Pull Request but I guess it's easier fo you just to include it yourself :)

**Comment by andreymal** [comment]
Since 19.2 it's `kodi.bin` again
